---
title: "Super Awesome Project Template"
output: word_document
date: "2023-03-31"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(tibble)
library(tidyr)
library(utils)
library(dplyr)
library(googleway)
library(httr)
library(magrittr)
```

```{r student3}
#James Bartsch
#dice with unique doubles/triples results
roll<<-function() {
  die <- sample(1:6, 6, replace = T)
  if(die[1] == die[2]){
    total_sum<<-sum(die[1:2])
    return(total_sum)
  }
  if( die[3] == die[4]){
    print("double")
  total_sum<<-sum(die[1:4])
    return(total_sum)}
if(die[5] == die[6]){
  total_sum<<-0
    print("triple")
  print("go to jail")
  return(total_sum)
}}
```


```{r}

reset_board <- function() {
  new_board_squares <<- NULL
  
  tiles <- c("Go", "Mediterranean Avenue", "Community Chest", "Baltic Avenue", "Income Tax", 
             "Reading Railroad", "Oriental Avenue", "Chance", "Vermont Avenue", "Connecticut Avenue", 
             "Jail", "St. Charles Place", "Electric Company", "States Avenue", "Virginia Avenue", 
             "Pennsylvania Railroad", "St. James Place", "Community Chest", "Tennessee Avenue", 
             "New York Avenue", "Free Parking", "Kentucky Avenue", "Chance", "Indiana Avenue", 
             "Illinois Avenue", "B&O Railroad", "Atlantic Avenue", "Ventnor Avenue", "Water Works", 
             "Marvin Gardens", "Go to Jail", "Pacific Avenue", "North Carolina Avenue", "Community Chest", 
             "Pennsylvania Avenue", "Short Line Railroad", "Chance", "Park Place", "Luxury Tax", "Boardwalk")

  board_squares <- tibble("Tile Name" = tiles, Class = NA, Occupants = NA, Owner = 'bank',"Mortgage Price" = c(0, 30, 0, 30, 0, 100, 50, 0, 50, 60,0, 70, 75, 70, 80, 100, 90, 0, 90,100, 0, 110, 0, 110, 120, 100, 130, 130,75,140, 0, 150, 150, 0, 160, 100, 0,175, 0, 200),  "Part of Monopoly" = NA, Description = NA, "Cost to Occupy" = NA, 'Color Set' = NA, "Number of Houses" = NA,"Hotels" = NA)

  board_squares$Class[board_squares$`Tile Name` %in% c("Mediterranean Avenue", "Baltic Avenue", "Oriental Avenue", "Vermont Avenue", "Connecticut Avenue", "St. Charles Place", "States Avenue", "Virginia Avenue", "St. James Place", "Tennessee Avenue", "New York Avenue", "Kentucky Avenue", "Indiana Avenue", "Illinois Avenue", "Atlantic Avenue", "Ventnor Avenue", "Marvin Gardens", "Pacific Avenue", "North Carolina Avenue", "Pennsylvania Avenue", "Park Place", "Boardwalk")] <- "Property Tile"
  board_squares$Class[board_squares$`Tile Name` %in% c("Electric Company", "Water Works")] <- "Utility Tile"
  board_squares$Class[board_squares$`Tile Name` %in% c("Reading Railroad", "Pennsylvania Railroad", "B&O Railroad", "Short Line Railroad")] <- "Railroad Tile"
  board_squares$Class[board_squares$`Tile Name` %in% c("Chance")] <- "Chance Tile"
  board_squares$Class[board_squares$`Tile Name` %in% c("Community Chest")] <- "Community Chest Tile"
  board_squares$Class[board_squares$`Tile Name` %in% c("Go")] <- "Go Tile"
  board_squares$Class[board_squares$`Tile Name` %in% c("Luxury Tax")] <- "Luxury Tax"
  board_squares$Class[board_squares$`Tile Name` %in% c("Income Tax")] <- "Income Tax"
  board_squares$Class[board_squares$`Tile Name` %in% c("Go to Jail")] <- "Go to Jail Tile"
  board_squares$Class[board_squares$`Tile Name` %in% c("Jail")] <- "Jail"
  board_squares$Class[board_squares$`Tile Name` %in% c("Free Parking")] <- "Free Parking"

  new_board_squares <<- board_squares

  View(new_board_squares)
}
reset_board()

```



```{r}
player_select <-function(...){
############################################################################################################################
token_selection<-function(...) {#takes a 2 to 4 values, either the name of a piece or a ?, and outputs those pieces as a character vector
  
as.character(c(...))
  
  #list of pieces
  pieces <- c("ace of spades","airplane","alarm clock","alligator","anvil","baby dinosaur","bag of money","balloon","baseball glove","basket","battleship","beach cruiser bike","bear","bicycle","boat","boot","bowtie","cactus","cannon","car","cat","cell phone","cheeseburger","chef's hat","chicken","computer","conductor's hat","cowboy hat","crab","crown","crystal","diamond","diamond ring","dice","dog","donut","dragon","duck","ducky","earmuffs","earth","egg","electric guitar","elephant","empanada","fire hydrant","fish","fishing pole","football","football helmet","frankenstein","french fries","frog","ghost","giant panda","gingerbread man","giraffe","globe","goldfish","golf bag","gondola","graduation cap","grapes","guitar","hammer","handcuffs","happy meal","hard hat","hashtag","hat","helicopter","hot air balloon","hot dog","horse and rider","horse shoe","ice cream cone","iron","jet plane","kangaroo","kettle","key","keyboard","king","kitty","koala","lantern","laptop","lighthouse","limousine","lion","little red wagon","locomotive","london bus","magic lamp","magnet","mallard duck","mallet","maple leaf","matchstick","metal car","microphone","money bag","monster truck","moon rover","motorcycle","mr. monopoly","music note","new balance sneaker","panda","penguin","phone","piece of cake","piggy bank","pineapple","plane","pretzel","pumpkin","racecar","razor","robot","roller skate","rooster","rubber ducky","sailboat","saxophone","scottie dog","shoe","skateboard","spaceship","spoon","sports car","stack of cash","star","statue of liberty","stethoscope","strawberry","sunflower","sunglasses","surfboard","taco","thimble","top hat","t-rex","tree","trolley car","trumpet","turtle","tv","typewriter","umbrella","wheelbarrow")
  
  #Changes everything to lower case in case input has different formatting
  names <- tolower(c(...))
  
  #Check that there are between 2 and 4 names
  if (length(names) < 2 || length(names) > 4) {
    message("Please input between 2 and 4 valid Monopoly piece names")
    return(NULL)
  }
  
  #Check that each name is a valid Monopoly piece or "?"
  valid_pieces <- c(pieces, "?")
  for (name in names) {
    if (!(name %in% valid_pieces)) {
      message("Invalid Monopoly piece name: ", name)
      return(NULL)
    }
  }
  
  # Assigns a random piece to any "?" inputs
  if ("?" %in% names) {
    chosen_pieces <- unique(names[names != "?"])
    available_pieces <- setdiff(pieces, chosen_pieces)
    random_pieces <- sample(available_pieces, length(names[names == "?"]), replace = F)
    names[names == "?"] <- random_pieces
  }
  
  # Creates a tibble of Player_Number and Name
  player_num <- 1:length(names)
  tibble(Player_Number = player_num, Name = names)
}
############################################################################################################################
assign_player_stats <<- function(...){#uses initial input of player_select function
  
  # Combine the names into a vector
  names<-c(...)
  # Generate random scores for each player
  scores <<- sample(1:6, length(names) * 2, replace = TRUE)
  scores <<- tapply(scores, rep(1:length(names), each = 2), sum)
  
  # Combine the names and scores into a tibble
  player_stats <<- tibble(Name = names, Score = scores)
  
  # Sort the tibble by score in descending order
  player_stats <<- player_stats[order(-player_stats$Score), ]
  
  # Assign the player numbers
  player_stats$Player_Number <<- 1:nrow(player_stats)
  
  # Return the tibble with only two columns
  player_stats<<-na.omit(player_stats[1:4, c("Player_Number", "Name")])
  
  player_stats %>%
  mutate(Money = NA_real_,Location = NA_character_,
         'Owned Properties' = NA_character_,'Houses' = 0,'Hotels' = 0, 'Jail' = 0) ->> player_stats#adds the columns Money, Location and Owned Properties to the player_stats tibble, then defines the player stats tibble globally
}
token_selection("?","?","?","?")$Name%>%assign_player_stats()

return(player_stats)
}
```

```{r}

#card effects(birthday card need to be worked on, get out of jail free needs to update a stat indicating that, birthday card needs to remove $10 from each other player as well,


reset_CommunityChestCards<<-function(){#globably defines the reset_CommunityChestCards function
  removed_community_cards <<- data.frame(matrix(ncol = 0, nrow = 0))
  CommunityChestCards <- data.frame(index = 1:16,card = c("Advance to Go (Collect $200)", "Bank error in your favor. Collect $200", "Doctor’s fee. Pay $50", "From sale of stock you get $50", "Get Out of Jail Free", "Go to Jail. Go directly to jail, do not pass Go, do not collect $200", "Holiday fund matures. Receive $100", "Income tax refund. Collect $20", "It is your birthday. Collect $10 from every player", "Life insurance matures. Collect $100", "Pay hospital fees of $100", "Pay school fees of $50", "Receive $25 consultancy fee", "You are assessed for street repair. $40 per house. $115 per hotel", "You have won second prize in a beauty contest. Collect $10", "You inherit $100"))
CommunityChestCards%>% select(-index) %>% mutate(#assign player who drew it, then assign that value to street repair
  Money = c(200, 200, -50, 50, NA, NA, 100, 20, 10*(nrow(player_stats)-1), 100, -100, -50, 25,-40*(player_stats[[player_turn,"Houses"]])-115*(player_stats[[player_turn,"Hotels"]]), 10, 100),
  Location = c(1, NA, NA, NA, NA, 31, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA), 'Drew By' = NA_character_) ->> CommunityChestCards
}
############################################################################################################################

reset_ChanceCards<<-function(){#globably defines the reset_ChanceCards function
  removed_Chance_cards <<- data.frame(matrix(ncol = 0, nrow = 0))
  ChanceCards <<- data.frame(index = 1:16,card = c("Advance to Boardwalk. ",
  "Advance to Go (Collect $200).",
  "Advance to Illinois Ave. If you pass Go, collect $200.",
  "Advance to St. Charles Place. If you pass Go, collect $200.",
  "Advance token to nearest Utility. If unowned, you may buy it from the Bank. If owned, throw dice and pay owner a total ten times amount thrown.",
  "Advance token to nearest Railroad. If unowned, you may buy it from the Bank. If owned, pay owner twice the rental to which they are otherwise entitled.",
  "Bank pays you dividend of $50.",
  "Get Out of Jail Free",
  "Go Back 3 Spaces.",
  "Go to Jail. Go directly to Jail, do not pass Go, do not collect $200.",
  "Make general repairs on all your property. For each house pay $25. For each hotel pay $100.",
  "Pay poor tax of $15.",
  "Take a trip to Reading Railroad. If you pass Go, collect $200.",
  "Take a walk on the Boardwalk. Advance token to Boardwalk.",
  "You have been elected Chairman of the Board. Pay each player $50.",
  "Your building and loan matures. Collect $150."
))
ChanceCards%>% select(-index) %>% mutate(#assign player who drew it, then assign that value to street repair
  Money = c(NA, 200, 200, 200, NA, NA, 50, NA, NA, NA, -15, 200, NA, NA, 50, 150),
  Location = c(40, 1, 24, 11, NA, NA, NA, NA, -3, 31, NA, 5, NA, 15, 40, NA)) ->> ChanceCards
}

```


```{r}
game_setup<-function(){#does the the first steps of any monopoly game
  bank<<-tibble(Money = 15140,houses = 32, hotels = 12)#defines the possessions of the bank globally 
bank$Money<<- bank$Money-1500*nrow(player_stats)#subtracts money from the bank corresponding to 1500 for each player playing
player_stats$Money<<- 1500#gives each player 1500
player_stats$Location<<-1#places each player at Go to start the game
player_turn<<-c(1)#sets the player turn number globably so other functions (move_player) and draw_community card can act on the correct player
total_turns<<-c(0)#sets the total turns as 1, allowing further tacking of number of turns played if necessary
}

```

```{r}
#Game setup
player_select("?","?","?","?")->player_stats
reset_board()
game_setup()
reset_CommunityChestCards()
reset_ChanceCards()
get_out_of_jail_card <<- c()
player_stats#visualize board
new_board_squares$Occupants<-list(character())
new_board_squares$Occupants[1]<-list(player_stats$Name)#Defines the Occupants of the board squares as a character vector of all the players occupying the tile



```


```{r}
#Define functions to draw cards

Draw_Community_Card <- function() {
  if (nrow(CommunityChestCards) < 1) {#what to do when last card is drawn
    return(c("out of cards"))
  }
  community_card_drew <- sample(1:nrow(CommunityChestCards), 1)#picks 1 card from the available number of cards(rows), returns the row number of the selected card
  community_card<-CommunityChestCards[community_card_drew, ]#define which card was drawn as community_card
  community_card[1,'Drew By']<-player_turn#update the 'Drew By' element of that card to log who drew it
  
  # Check if the drawn card is 'Get Out of Jail Free'
  if (community_card$card == 'Get Out of Jail Free') {
    get_out_of_jail_card <<- c(get_out_of_jail_card, player_turn) # Create a global vector with the value player_turn
  }
  
  #logs which card was removed
  removed_community_cards<<-rbind(removed_community_cards, community_card)#add that card to the global list of drawn community cards
  
  CommunityChestCards <<- CommunityChestCards[-community_card_drew, ]#remove the card from the available community cards globally 
  return(community_card)#display the drawn card 
}


############################################################################################################################


Draw_Chance_Card <- function() {
  if (nrow(ChanceCards) < 1) {#what to do when last card is drawn
    return(c("out of cards"))
  }
 Chance_card_drew <- sample(1:nrow(ChanceCards), 1)#picks 1 card from the available number of cards(rows), returns the row number of the selected card
  Chance_card<-ChanceCards[Chance_card_drew, ]#define which card was drawn as community_card
  Chance_card[1,'Drew By']<-player_turn#update the 'Drew By' element of that card to log who drew it
  
  if (Chance_card$card == 'Get Out of Jail Free') {
    get_out_of_jail_card <<- c(get_out_of_jail_card, player_turn) # Create a global vector with the value player_turn
  }
  
  #logs which card was removed
  removed_Chance_cards<<-rbind(removed_Chance_cards, Chance_card)#add that card to the global list of drawn community cards
  
  ChanceCards <<- ChanceCards[-Chance_card_drew, ]#remove the card from the available community cards globally 
  return(Chance_card)#display the drawn card 
}

############################################################################################################################


Purchase_Tile<-function(){#everything in the purchase bit is the same just now it is for a utility tile
  
  player_stats[player_turn, "Money"] <<- player_stats[player_turn, "Money"] - 2 * new_board_squares[new_location, "Mortgage Price"]
  bank$Money <<- bank$Money + 2 * new_board_squares[[new_location, "Mortgage Price"]]
  purchased <- paste("Player: ", player_stats$Name[player_turn], "bought", new_board_squares[new_location, "Tile Name"])
  new_board_squares[new_location, "Owner"] <<- player_stats[player_turn, "Name"]
  
  # Update the 'Owned Properties' entry for the current player
  if(is.na(player_stats[player_turn, "Owned Properties"])) {
    player_stats[player_turn, "Owned Properties"] <<- new_board_squares[new_location, "Tile Name"]
  } else {
    player_stats[player_turn, "Owned Properties"] <<- paste(player_stats[player_turn, "Owned Properties"], new_board_squares[new_location, "Tile Name"], sep=", ")
  }
  
  print(purchased)
}


```


```{r}
#this one
move_player <- function() {
  while (!is.na(player_stats[player_turn, "Jail"]) && player_stats[player_turn, "Jail"] > 0) {
  if (length(unique(sample(1:6,2, replace = T))) == 1){
    print("Lucky Roll, Get Out of Jail")
    player_stats[player_turn, 'Jail'] <<- 0
    player_stats[player_turn, 'Money'] <<- player_stats[player_turn, 'Money'] - 50 
    bank$Money <<- bank$Money + 50
  } else if (player_turn %in% get_out_of_jail_card){
    get_out_of_jail_card <<- get_out_of_jail_card[-which(get_out_of_jail_card == player_turn)]
    cat(paste(player_stats[player_turn, 'Name'], "Used Get Out of Jail Free Card\n"))
    player_stats[player_turn, 'Jail'] <<- 0
  } else if (player_stats[player_turn, 'Jail'] > 3){
    print("Get Out of Jail")
    player_stats[player_turn, 'Jail'] <<- 0
    player_stats[player_turn, 'Money'] <<- player_stats[player_turn, 'Money'] - 50 
    bank$Money <<- bank$Money + 50
  } else {
    player_stats[player_turn, 'Jail'] <<- player_stats[player_turn, 'Jail'] + 1
    cat(paste(player_stats[player_turn, 'Name'], "Is Stuck in Jail\n"))
    player_turn <<- player_turn + 1  # Increment player_turn by 1
    if (player_turn > nrow(player_stats)) {
      player_turn <<- 1  # Reset player_turn to 1 if it exceeds the number of rows in player_stats
    } 
  }
}

  total_sum <<- roll()  # rolls dice to determine spaces to move
  print(total_sum)  # prints dice roll result
  new_location <<- player_stats[[player_turn, "Location"]] + total_sum  # moves the player, defined by player_turn, to the new location

  # First check
  if (new_location > 40) {  # checks if the player passes 40th square
    new_location <<- new_location - 40  # removes 40 from total position corresponding to lapping the board
    player_stats[player_turn, "Money"] <<- player_stats[player_turn, "Money"] + 200  # adds 200 dollars to that player_stats money
    bank$Money <<- bank$Money - 200  # takes away the money from the bank
    passed_Go <- c("Player: ", player_stats$Name[player_turn], "passed Go")
    print(passed_Go)  # announces player passed go
  }
  
  # Second check
  if (total_sum == 0 || new_location == 31) {  # conditions for going to jail
    new_location <- 11  # sends player to jail
   player_stats[player_turn, 'Jail']<<-1 
  }

  # Third check
  current_square <- new_board_squares[new_location, ]
  current_class <- current_square$Class

   if (current_class == "Railroad Tile") {#standin function to make sure things are working
    print("Railroad Tile")
     if(new_board_squares[new_location, "Owner"] == 'bank' & player_stats[player_turn, "Money"] > 2 * new_board_squares[new_location, "Mortgage Price"]) {
       
  Purchase_Tile()
    }
     
     
     
     ########################need to add conditions for:  player is on an unowned tile and doesnt have enough money,player is on an owned tile of someone with multiple other railroads
     
  } else if (current_class == "Chance Tile") {#if the class of the current location tile is a Chance Tile
    Draw_Chance_Card()#run the Draw_Chance_Card function which randomly selects a card from the available chance cards, removes that card from the available chance cards, assigns that card to the current player (need to have another function actually make use of the information of the assigned card to)
    print("Chance Tile")
    
  } else if (current_class == "Community Chest Tile") {
    Draw_Community_Card()#run the Draw_Community_Card function which randomly selects a card from the available community cards, removes that card from the available community cards, assigns that card to the current player (need to have another function actually make use of the information of the assigned card to)
    print("Community Chest Tile")
    
  } else if (current_class == "Go Tile") {#if the class of the current location tile is a Go Tile
    #(nothing should happen)
    print("Go Tile")
    
  } else if (current_class == "Luxury Tax") {#if the class of the current location tile is a Luxury Tax Tile
    print("Luxury Tax") #states the current tile
    player_stats[[player_turn, "Money"]]<<- player_stats[[player_turn, "Money"]]- 75#take 75 dollars from the player
    bank$Money <<- bank$Money + 75 #gives 75 dollars to the bank
    
    
  } else if (current_class == "Income Tax") {#if the class of the current location tile is a Income Tax Tile
    player_stats[[player_turn, "Money"]]<<- player_stats[[player_turn, "Money"]] -200#takes 200 dollars from the player
    bank$Money <<- bank$Money + 200#gives 200 dollars to the bank
    print("Income Tax")
    
  } else if (current_class == "Go to Jail Tile") {#this won't ever happen
    #this won't ever happen as the "Go to Jail" function is already integrated in a earlier step 
    print("Go to Jail Tile")
    
  } else if (current_class == "Jail") {#if current location is Jail
    #the player is just visiting if they land on the jail tile without being sent there
    if (total_sum != 0 || new_location != 31) {
      print("Just Visitng")} 
    
  } else if (current_class == "Free Parking") {#if the class of the current location tile is a Free Parking Tile
    #(nothing should happen)
    print("Free Parking")
    
  } else if (current_class == "Property Tile") {#if the class of the current location tile is a Property Tile
    print("Property Tile")
    if(new_board_squares[new_location, "Owner"] == 'bank' & player_stats[player_turn, "Money"] > 2 * new_board_squares[new_location, "Mortgage Price"]) {
      
      Purchase_Tile()
    }
    
    
  } else if (current_class == "Utility Tile") {#if the class of the current location tile is a utility
    print("Utility Tile")
    
    if(new_board_squares[new_location, "Owner"] == 'bank' & player_stats[player_turn, "Money"] > 2 * new_board_squares[new_location, "Mortgage Price"]) {#everything in the purchase bit is the same just now it is for a utility tile
  
      Purchase_Tile()
    }
    
  }
  # Update the tibble with the new location
  temp_board_squares <- new_board_squares %>%
    mutate(Occupants = map(Occupants, ~ .x[.x != player_stats$Name[player_turn]]))  # removes current player from vector of occupants on current tile
  new_board_squares <<- temp_board_squares %>%
    mutate(Occupants = map_at(Occupants, new_location, ~ if (is.na(.x) || length(.x) == 0) {
      c(player_stats$Name[player_turn])
    } else {
      c(.x, player_stats$Name[player_turn])
    }))
player_stats[[player_turn, "Location"]]<<- new_location
  
player_turn <<- player_turn + 1  # Increment player_turn by 1
  if (player_turn > nrow(player_stats)) {
    player_turn <<- 1  # Reset player_turn to 1 if it exceeds the number of rows in player_stats
  } 
  return(list(player_stats = player_stats, new_location = new_location))  # displays the new player_stats stat
}

```

```{r}
#needs more testing
Purchase_Tile<-function(){#everything in the purchase bit is the same just now it is for a utility tile
  
  player_stats[player_turn, "Money"] <<- player_stats[player_turn, "Money"] - 2 * new_board_squares[new_location, "Mortgage Price"]
  bank$Money <<- bank$Money + 2 * new_board_squares[[new_location, "Mortgage Price"]]
  purchased <- paste("Player: ", player_stats$Name[player_turn], "bought", new_board_squares[new_location, "Tile Name"])
  new_board_squares[new_location, "Owner"] <<- player_stats[player_turn, "Name"]
  
  # Update the 'Owned Properties' entry for the current player
  if(is.na(player_stats[player_turn, "Owned Properties"])) {
    player_stats[player_turn, "Owned Properties"] <<- new_board_squares[new_location, "Tile Name"]
  } else {
    player_stats[player_turn, "Owned Properties"] <<- paste(player_stats[player_turn, "Owned Properties"], new_board_squares[new_location, "Tile Name"], sep=", ")
  }
  
  print(purchased)
}

#Purchase_House<-function(){

```

